include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    file_names: false
    public_member_api_docs: false
    flutter_style_todos: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    always_put_required_named_parameters_first: false
