name: app
description: Ejimo - Comprehensive emoji and symbol picker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+9

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0

  json_annotation: ^4.8.0

  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.4

  # UI
  cupertino_icons: ^1.0.4
  flex_color_scheme: ^7.0.1
  google_fonts: ^4.0.3
  sliver_tools: ^0.2.10
  slivers: ^0.0.1+2
  super_responsive: ^0.1.6
#  responsive_builder: ^0.4.3

  emojis: ^0.9.9

  # search
  fuzzywuzzy: ^0.2.0
  easy_debounce: ^2.0.3

  clipboard: ^0.1.3
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  package_info_plus: ^3.1.0
  cross_platform: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.1

  http: ^0.13.4
  # linting
  very_good_analysis: ^4.0.0+1
  # app icons
  flutter_launcher_icons_maker: ^0.10.2
  # windows
  msix: ^3.7.0
  # build scripts
  flutter_build_helpers:
    git:
      url: https://github.com/albemala/flutter_build_helpers.git
      ref: 9f15d7049f048eba9c2b8d62730e8e473e0dec41

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - google_fonts/

# flutter pub run flutter_launcher_icons_maker:main && flutter clean
flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/app-icon.png"
  image_path_ios: "assets/app-icon-ios.png"
  adaptive_icon_background: "#000000"
#  adaptive_icon_background: "assets/app-icon/android-background.png"
  adaptive_icon_foreground: "assets/app-icon-android-foreground.png"

msix_config:
  # Windows Store
  msix_version: 1.3.0.0
  # App
  display_name: Ejimo
  logo_path: assets/images/app-icon.png
  start_menu_icon_path: assets/images/app-icon.png
  tile_icon_path: assets/images/app-icon.png
  icons_background_color: transparent
  languages: en-us
  architecture: x64
