name: app
description: Ejimo - Comprehensive emoji and symbol picker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3

  cupertino_icons: ^1.0.4
  flex_color_scheme: ^4.2.0
  google_fonts: ^2.3.1

  emojis: ^0.9.9

  fuzzywuzzy: ^0.2.0

  clipboard: ^0.1.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linting
  very_good_analysis: ^2.4.0

  flutter_launcher_icons:
    git:
      url: https://github.com/kechankrisna/flutter_launcher_icons.git
      ref: b54d5244566c59dc5e98fb7dd28a245999600d0f

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - google_fonts/

# fvm flutter pub run flutter_launcher_icons:main && fvm flutter clean
flutter_icons:
  android: false
  ios: false
  macos: true
#  windows: true
  image_path: "assets/images/app-icon.png"
  image_path_macos: "assets/images/app-icon.png"
