name: app
description: Ejimo - Comprehensive emoji and symbol picker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.1

  json_annotation: ^4.8.1

  flutter_state_management:
    git:
      url: https://github.com/albemala/flutter_state_management
      ref: 2.0.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0

  # UI
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.2.0
  google_fonts: ^4.0.3
  sliver_tools: ^0.2.12
  slivers: ^0.0.1+2

  # search
  fuzzywuzzy: ^0.2.0
  easy_debounce: ^2.0.3

  package_info_plus: ^4.0.2
  cross_platform: ^3.0.1
  clipboard: ^0.1.3

  url_launcher: ^6.1.14
  in_app_review: ^2.0.6
  share_plus: ^7.1.0
  send_support_email:
    git:
      url: https://github.com/albemala/send_support_email.git
      ref: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  http: ^1.1.0
  # linting
  very_good_analysis: ^5.0.0+1
  # app icons
  flutter_launcher_icons_maker: ^0.10.2
  package_rename: ^1.5.1
  # windows
  msix: ^3.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/fonts/TitilliumWeb/
    - assets/images/

# flutter pub run flutter_launcher_icons_maker:main && flutter clean
flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/app-icon.png"
  image_path_ios: "assets/app-icon-ios.png"
  adaptive_icon_background: "#000000"
#  adaptive_icon_background: "assets/app-icon/android-background.png"
  adaptive_icon_foreground: "assets/app-icon-android-foreground.png"

# dart run package_rename
package_rename_config:
  android:
    app_name: Ejimo
    package_name: me.albemala.ejimo
  ios:
    app_name: Ejimo
    bundle_name: Ejimo
    package_name: me.albemala.ejimo
  macos:
    app_name: Ejimo
    package_name: me.albemala.ejimo
    copyright_notice: Copyright © 2023 Alberto Malagoli (albemala.me). All rights reserved.
  windows:
    app_name: Ejimo
    organization: albemala.me
    copyright_notice: Copyright © 2023 Alberto Malagoli (albemala.me).
    exe_name: Ejimo
  linux:
    app_name: Ejimo
    package_name: me.albemala.ejimo
    exe_name: Ejimo
  web:
    app_name: Ejimo
    description: Find and copy unicode characters, emoji, kaomoji and symbols with Ejimo.

msix_config:
  # Windows Store
  msix_version: 1.3.0.0
  # App
  display_name: Ejimo
  logo_path: assets/images/app-icon.png
  start_menu_icon_path: assets/images/app-icon.png
  tile_icon_path: assets/images/app-icon.png
  icons_background_color: transparent
  languages: en-us
  architecture: x64
