name: app
description: Ejimo - Comprehensive emoji and symbol picker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3

  # UI
  cupertino_icons: ^1.0.4
  flex_color_scheme: ^5.0.1
  google_fonts: ^3.0.1
  sliver_tools: ^0.2.5
  slivers: ^0.0.1+2
  super_responsive: ^0.1.6

  emojis: ^0.9.9

  # search
  fuzzywuzzy: ^0.2.0

  clipboard: ^0.1.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  package_info_plus: ^1.4.2
  cross_platform: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linting
  very_good_analysis: ^3.0.0

  flutter_launcher_icons_maker: ^0.10.2

  msix: ^3.5.1
  io: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - google_fonts/

# flutter pub run flutter_launcher_icons_maker:main && flutter clean
flutter_icons:
  android: false
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/app-icon.png"
  image_path_macos: "assets/images/app-icon.png"

msix_config:
  # Windows Store
  msix_version: 1.1.0.0
  # App
  display_name: Ejimo
  logo_path: assets/images/app-icon.png
  start_menu_icon_path: assets/images/app-icon.png
  tile_icon_path: assets/images/app-icon.png
  icons_background_color: transparent
  languages: en-us
  architecture: x64
