name: app
description: Ejimo - Comprehensive emoji and symbol picker.
version: 3.0.0+13

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  equatable: ^2.0.7
  fast_immutable_collections: ^11.0.0
  flutter_bloc: ^8.1.6
  # data storage
  shared_preferences: ^2.3.5

  # UI
  flex_color_scheme: ^8.0.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  sliver_tools: ^0.2.12
  slivers: ^0.0.1+2

  # search
  fuzzywuzzy: ^1.2.0
  easy_debounce: ^2.0.3

  # utils
  collection: ^1.18.0
  clipboard: ^0.1.3
  cross_platform: ^3.0.1

  package_info_plus: ^8.1.1
  device_info_plus: ^11.1.1
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  in_app_review: ^2.0.10
  send_support_email:
    git:
      url: https://github.com/albemala/send_support_email.git
      ref: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  # flutter test --update-goldens test/screenshots/take_screenshots_test.dart
  golden_screenshot: ^3.1.3

  very_good_analysis: ^7.0.0

  build_runner: ^2.4.13
  flutter_launcher_icons_maker: ^0.10.2
  package_rename: ^1.8.0

  http: ^1.2.0
  path: ^1.9.0

  # windows
  msix: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/TitilliumWeb/
    - assets/fonts/Noto_Color_Emoji/
    - assets/images/
  fonts:
    # https://github.com/notofonts/notofonts.github.io/tree/main/megamerge
    - family: Noto Sans Living
      fonts:
        - asset: assets/fonts/NotoSans/NotoSansLiving-Regular.ttf
          weight: 400
    # https://github.com/notofonts/noto-cjk/tree/main/Sans/SubsetOTF
    - family: Noto Sans Japanese
      fonts:
        - asset: assets/fonts/NotoSans/NotoSansJP-Regular.otf
          weight: 400
    - family: Noto Sans Korean
      fonts:
        - asset: assets/fonts/NotoSans/NotoSansKR-Regular.otf
          weight: 400
    - family: Noto Sans Simplified Chinese
      fonts:
        - asset: assets/fonts/NotoSans/NotoSansSC-Regular.otf
          weight: 400

# dart run flutter_launcher_icons_maker:main && flutter clean && flutter pub get
flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/app-icon.png"
  image_path_ios: "assets/app-icon-ios.png"
  adaptive_icon_background: "#000000"
#  adaptive_icon_background: "assets/app-icon/android-background.png"
  adaptive_icon_foreground: "assets/app-icon-android-foreground.png"

# dart run package_rename
package_rename_config:
  android:
    app_name: Ejimo
    package_name: me.albemala.ejimo
  ios:
    app_name: Ejimo
    bundle_name: Ejimo
    package_name: me.albemala.ejimo
  macos:
    app_name: Ejimo
    package_name: me.albemala.ejimo
    copyright_notice: Copyright © 2025 Alberto Malagoli (albemala.me). All rights reserved.
  windows:
    app_name: Ejimo
    organization: albemala.me
    copyright_notice: Copyright © 2025 Alberto Malagoli (albemala.me).
    exe_name: Ejimo
  linux:
    app_name: Ejimo
    package_name: me.albemala.ejimo
    exe_name: Ejimo
  web:
    app_name: Ejimo
    description: Find and copy unicode characters, emoji, kaomoji and symbols with Ejimo.

msix_config:
  # Windows Store
  msix_version: 2.0.2.0
  # App
  display_name: Ejimo
  logo_path: assets/images/app-icon.png
  start_menu_icon_path: assets/images/app-icon.png
  tile_icon_path: assets/images/app-icon.png
  icons_background_color: transparent
  languages: en-us
  architecture: x64