name: app
description: Ejimo - Comprehensive emoji and symbol picker.
version: 2.0.2+12

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0

  json_annotation: ^4.8.1

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # UI
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  sliver_tools: ^0.2.12
  slivers: ^0.0.1+2

  # search
  fuzzywuzzy: ^1.1.6
  easy_debounce: ^2.0.3

  package_info_plus: ^5.0.1
  cross_platform: ^3.0.1
  clipboard: ^0.1.3

  url_launcher: ^6.2.2
  in_app_review: ^2.0.8
  share_plus: ^7.2.1
  send_support_email:
    git:
      url: https://github.com/albemala/send_support_email.git
      ref: 1.3.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter

  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  http: ^1.1.2
  # linting
  very_good_analysis: ^5.1.0
  # app icons
  flutter_launcher_icons_maker: ^0.10.2
  package_rename: ^1.5.3
  # windows
  msix: ^3.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/fonts/TitilliumWeb/
    - assets/images/

# dart run flutter_launcher_icons_maker:main && flutter clean && flutter pub get
flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/app-icon.png"
  image_path_ios: "assets/app-icon-ios.png"
  adaptive_icon_background: "#000000"
#  adaptive_icon_background: "assets/app-icon/android-background.png"
  adaptive_icon_foreground: "assets/app-icon-android-foreground.png"

# dart run package_rename
package_rename_config:
  android:
    app_name: Ejimo
    package_name: me.albemala.ejimo
  ios:
    app_name: Ejimo
    bundle_name: Ejimo
    package_name: me.albemala.ejimo
  macos:
    app_name: Ejimo
    package_name: me.albemala.ejimo
    copyright_notice: Copyright © 2023 Alberto Malagoli (albemala.me). All rights reserved.
  windows:
    app_name: Ejimo
    organization: albemala.me
    copyright_notice: Copyright © 2023 Alberto Malagoli (albemala.me).
    exe_name: Ejimo
  linux:
    app_name: Ejimo
    package_name: me.albemala.ejimo
    exe_name: Ejimo
  web:
    app_name: Ejimo
    description: Find and copy unicode characters, emoji, kaomoji and symbols with Ejimo.

msix_config:
  # Windows Store
  msix_version: 2.0.2.0
  # App
  display_name: Ejimo
  logo_path: assets/images/app-icon.png
  start_menu_icon_path: assets/images/app-icon.png
  tile_icon_path: assets/images/app-icon.png
  icons_background_color: transparent
  languages: en-us
  architecture: x64
