platform :mac do

  lane :generate_certificates_profiles do |options|
    match(
      type: "development",
#       force_for_new_devices: true,
    )
    match(
      type: "appstore",
    )
    match(
      type: "developer_id",
      additional_cert_types: [
        "mac_installer_distribution",
        "developer_id_installer",
      ],
    )
  end

  lane :get_certificates_profiles do |options|
    match(
      type: "development",
      readonly: true,
    )
    match(
      type: "appstore",
      readonly: true,
    )
    match(
      type: "developer_id",
      additional_cert_types: [
        "mac_installer_distribution",
        "developer_id_installer",
      ],
      readonly: true,
    )
  end

  lane :build_app_store do |options|
    build_mac_app(
      scheme: "Runner",
      export_method: "app-store",
      export_team_id: ENV["TEAM_ID"],
      export_options: {
        provisioningProfiles: {
          "me.albemala.ejimo" => "match AppStore me.albemala.ejimo macos",
        },
      },
      output_directory: "build",
    )
  end

  lane :build_standalone do |options|
    build_mac_app(
      scheme: "Runner",
      export_method: "developer-id",
      export_team_id: ENV["TEAM_ID"],
      export_options: {
        provisioningProfiles: {
          "me.albemala.ejimo" => "match Direct me.albemala.ejimo macos",
        },
      },
      output_directory: "build",
    )
  end

  lane :publish_app_store do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_KEY_ID"],
      issuer_id: ENV["APPLE_ISSUER_ID"],
      key_filepath: ENV["APPLE_KEY_FILEPATH"],
#       duration: 1200, # optional (maximum 1200)
#       in_house: false # optional but may be required if using match/sigh
    )
    upload_to_app_store(
      pkg: "build/Ejimo.pkg",
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
    )
  end

  lane :publish_standalone do |options|
    notarize(
      asc_provider: ENV["TEAM_ID"],
      package: "build/Ejimo.app",
      print_log: true,
      verbose: true,
    )
  end

end
