platform :mac do

  lane :app_store do
    build_mac_app(
      scheme: "Runner",
      export_method: "app-store",
      export_team_id: ENV["TEAM_ID"],
      export_options: {
        provisioningProfiles: {
          "me.albemala.ejimo" => "Ejimo - App Store - Mac App Distribution",
        },
      },
      output_directory: "build",
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

  lane :standalone do
    build_mac_app(
      scheme: "Runner",
      export_method: "developer-id",
      export_team_id: ENV["TEAM_ID"],
      export_options: {
        provisioningProfiles: {
          "me.albemala.ejimo" => "Ejimo - Developer ID Application",
        },
      },
      output_directory: "build",
    )
    notarize(
      asc_provider: ENV["TEAM_ID"],
      package: "./build/Ejimo.app",
      print_log: true,
      verbose: true,
    )
  end

end
