repository_name = "albemala/emoji-picker"

lane :create_release do |options|
    version = options[:version]
    release = get_github_release(
        url: repository_name,
        version: version
    )
    if release == nil
        set_github_release(
            repository_name: repository_name,
            api_token: ENV["GITHUB_TOKEN"],
            name: "v#{version}",
            tag_name: "v#{version}",
            commitish: "main",
            description: "",
        )
    end
end
