platform :ios do

  lane :generate_certificates_profiles do |options|
    match(
      type: "development",
#       force_for_new_devices: true,
    )
    match(
      type: "appstore",
    )
  end

  lane :get_certificates_profiles do |options|
    match(
      type: "development",
      readonly: true,
    )
    match(
      type: "appstore",
      readonly: true,
    )
  end

  lane :build do |options|
    build_ios_app(
      scheme: "Runner",
      export_method: "app-store",
#       export_options: {
#         provisioningProfiles: {
#           "me.albemala.ejimo" => "match AppStore ...",
#         },
#       },
      output_directory: "build",
    )
  end

  lane :publish do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_KEY_ID"],
      issuer_id: ENV["APPLE_ISSUER_ID"],
      key_filepath: ENV["APPLE_KEY_FILEPATH"],
#       duration: 1200, # optional (maximum 1200)
#       in_house: false # optional but may be required if using match/sigh
    )
    upload_to_app_store(
      ipa: "build/Runner.ipa",
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
    )
  end

end
