platform :ios do

  lane :generate_certificates_profiles do |options|
    username = options[:username] # Apple ID
    match(
      username: username,
      type: "development",
    )
    match(
      username: username,
      type: "appstore",
    )
  end

  lane :get_certificates_profiles do |options|
#     keychain_name = options[:keychain_name] || "login.keychain"
    username = options[:username] # Apple ID
    match(
#       keychain_name: keychain_name,
      username: username,
      type: "development",
      readonly: true,
    )
    match(
#       keychain_name: keychain_name,
      username: username,
      type: "appstore",
      readonly: true,
    )
  end

  lane :build do |options|
    build_ios_app(
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "build",
    )
  end

  lane :publish do |options|
    upload_to_app_store(
      username: options[:username],
      app_identifier: "me.albemala.ejimo",
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

end
