platform :android do

  lane :publish do |options|
    upload_to_play_store(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      track: 'production',
      json_key: ENV["ANDROID_JSON_KEY_FILE"], # google auth key
    )
  end

end
